# Auto-generated by enclave build — do not edit.
terraform {
  backend "s3" {
    bucket         = "dev-my-app-tfstate-000000000000-us-east-1"
    key            = "terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "dev-my-app-tfstate-lock"
  }
}
