# Root module for the enclave CLI.
# Calls the reusable enclave module.
# Backend is configured in backend.tf (generated by enclave build).

terraform {
  required_version = ">= 1.6.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
}

provider "aws" {
  region = var.region

  default_tags {
    tags = {
      ManagedBy  = "opentofu"
      Deployment = var.deployment
      AppName    = var.app_name
    }
  }
}

# The enclave stack: KMS, IAM, VPC, EC2, SSM, S3.
module "enclave" {
  source = "./modules/enclave"

  region            = var.region
  account           = var.account
  deployment        = var.deployment
  app_name          = var.app_name
  instance_type     = var.instance_type
  local             = var.local
  secrets           = var.secrets
  migration_cooldown = var.migration_cooldown
  previous_pcr0     = var.previous_pcr0
  expected_pcr0     = var.expected_pcr0
  supervisor_url          = var.supervisor_url
  github_owner  = var.github_owner
  github_repo   = var.github_repo
  release_tag   = var.release_tag
  github_token  = var.github_token

  eif_path               = var.eif_path
  supervisor_binary_path = var.supervisor_binary_path
}
