package runtime

import (
	"context"
	"encoding/hex"
	"errors"
	"strings"

	sdk "thresholdsdk"
)

// thresholdRecoveryPrefix namespaces threshold recovery blobs in Storage.
const thresholdRecoveryPrefix = "threshold/recovery/"

// DkgStore implements thresholdsdk.Store over the enclave's encrypted
// Storage (S3 + AES-GCM DEK). It persists only the public recovery blobs a
// ceremony produces; no secret material is written. The leader's group secret a0
// is not generated by the SDK here — it is the master's KMS-managed static
// secret, supplied at construction, which is what makes the threshold group's
// reconstructed secret equal the normally-created secret.
type DkgStore struct {
	storage *Storage
	// leaderSecret is the master's full static secret, returned as a0 from
	// GetLeaderSecret. Nil on a follower (which never acts as leader).
	leaderSecret []byte
}

// newThresholdStore builds the adapter. leaderSecret is the master's decrypted
// static secret (nil for a follower).
func newThresholdStore(storage *Storage) *DkgStore {
	return &DkgStore{storage: storage}
}

func (s *DkgStore) recoveryKey(groupKey []byte) string {
	return thresholdRecoveryPrefix + hex.EncodeToString(groupKey)
}

func (s *DkgStore) PutRecovery(groupKey, blob []byte) error {
	return s.storage.Store(context.Background(), s.recoveryKey(groupKey), blob)
}

func (s *DkgStore) GetRecovery(groupKey []byte) ([]byte, error) {
	blob, err := s.storage.Load(context.Background(), s.recoveryKey(groupKey))
	if errors.Is(err, ErrNotFound) {
		return nil, sdk.ErrNotFound
	}
	return blob, err
}

func (s *DkgStore) Has(groupKey []byte) (bool, error) {
	_, err := s.storage.Load(context.Background(), s.recoveryKey(groupKey))
	if errors.Is(err, ErrNotFound) {
		return false, nil
	}
	if err != nil {
		return false, err
	}
	return true, nil
}

func (s *DkgStore) List() ([][]byte, error) {
	keys, err := s.storage.List(context.Background(), thresholdRecoveryPrefix)
	if err != nil {
		return nil, err
	}
	out := make([][]byte, 0, len(keys))
	for _, k := range keys {
		gk, derr := hex.DecodeString(strings.TrimPrefix(k, thresholdRecoveryPrefix))
		if derr != nil {
			continue // skip anything that isn't a hex-encoded group key
		}
		out = append(out, gk)
	}
	return out, nil
}

// GetLeaderSecret returns the master's static secret as the group secret a0.
// The SDK's Leader.secret() calls this first and only generates+persists a fresh
// a0 on ErrNotFound, so returning the KMS secret here pins the group key to it.
func (s *DkgStore) GetLeaderSecret() ([]byte, error) {
	if len(s.leaderSecret) == 0 {
		return nil, sdk.ErrNotFound
	}
	return s.leaderSecret, nil
}

// PutLeaderSecret is a no-op: the leader secret is externally managed (KMS), not
// generated by the SDK. It is never called while GetLeaderSecret returns a value.
func (s *DkgStore) PutLeaderSecret(a0 []byte) error { return nil }

// Close is a no-op: the underlying Storage lifecycle is owned by the Runtime.
func (s *DkgStore) Close() error { return nil }

// compile-time assertion that the adapter satisfies the SDK interface.
var _ sdk.Store = (*DkgStore)(nil)
