package cli

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"gopkg.in/yaml.v3"
)

const composeFilePath = "enclave/test/docker-compose.yml"

// userServicesMarker sits inside the services: map at 4-space indent
// so user-appended blocks at the same indent nest in the same map.
const userServicesMarker = `
    # === user services below this line ===
    # Append additional service blocks at 4-space indent so they nest
    # under the existing services: map. Do NOT add another "services:"
    # key. Wire boot ordering by adding the service name to
    # test-runner.depends_on. Example:
    #
    # mock-arkd:
    #     build:
    #         context: ../../
    #         dockerfile: enclave/test/mock-arkd/Dockerfile
    #     network_mode: host
    #     healthcheck:
    #         test: ["CMD-SHELL", "nc -z 127.0.0.1 8081 || exit 1"]
    #         interval: 5s
    #         retries: 5
`

type composeDoc struct {
	Services map[string]composeService `yaml:"services"`
}

type composeService struct {
	Image       string            `yaml:"image,omitempty"`
	Ports       []string          `yaml:"ports,omitempty"`
	Environment map[string]string `yaml:"environment,omitempty"`
	Volumes     []string          `yaml:"volumes,omitempty"`
	DependsOn   map[string]struct {
		Condition string `yaml:"condition"`
	} `yaml:"depends_on,omitempty"`
	Healthcheck *composeHealthcheck `yaml:"healthcheck,omitempty"`
	Privileged  bool                `yaml:"privileged,omitempty"`
	NetworkMode string              `yaml:"network_mode,omitempty"`
}

type composeHealthcheck struct {
	Test     []string `yaml:"test"`
	Interval string   `yaml:"interval,omitempty"`
	Timeout  string   `yaml:"timeout,omitempty"`
	Retries  int      `yaml:"retries,omitempty"`
}

// writeTestCompose generates the test compose file. Merge-only-new
// unless force=true.
func writeTestCompose(cfg *Config, projectRoot string, force bool) (written bool, err error) {
	target := filepath.Join(projectRoot, composeFilePath)
	if !force {
		if _, statErr := os.Stat(target); statErr == nil {
			return false, nil
		} else if !os.IsNotExist(statErr) {
			return false, fmt.Errorf("stat %s: %w", composeFilePath, statErr)
		}
	}

	version := strings.TrimPrefix(runtimeRev, "v")
	if version == "" {
		return false, fmt.Errorf("framework runtime version unknown; CLI was built without -ldflags " +
			"and runtime-hashes.json is empty — bake a version into the binary before generating a compose file")
	}
	doc := buildComposeDoc(cfg, version)

	out, err := yaml.Marshal(doc)
	if err != nil {
		return false, fmt.Errorf("marshal compose: %w", err)
	}

	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return false, fmt.Errorf("mkdir for %s: %w", composeFilePath, err)
	}
	body := append(composeFileHeader(version), out...)
	body = append(body, []byte(userServicesMarker)...)
	if err := os.WriteFile(target, body, 0o644); err != nil {
		return false, fmt.Errorf("write %s: %w", composeFilePath, err)
	}
	return true, nil
}

func composeFileHeader(frameworkVersion string) []byte {
	return []byte(fmt.Sprintf(`# Generated by 'enclave test init' for framework version %s.
# Re-runs of 'enclave test init' will SKIP this file if it exists.
# To regenerate from scratch (e.g. after bumping the framework
# version): 'enclave test init --force-compose'.
#
# Hand-add app-specific dependency containers below the marker at
# the bottom of this file.

`, frameworkVersion))
}

func buildComposeDoc(cfg *Config, frameworkVersion string) composeDoc {
	awsMocks := fmt.Sprintf("ghcr.io/arklabshq/enclave-awsmocks:%s", frameworkVersion)
	testRunner := fmt.Sprintf("ghcr.io/arklabshq/enclave-test-runner:%s", frameworkVersion)

	healthy := map[string]struct {
		Condition string `yaml:"condition"`
	}{
		"local-kms":  {Condition: "service_healthy"},
		"aws-mocks":  {Condition: "service_healthy"},
		"localstack": {Condition: "service_healthy"},
	}

	return composeDoc{
		Services: map[string]composeService{
			"local-kms": {
				Image: "nsmithuk/local-kms",
				Ports: []string{"8080:8080"},
				Environment: map[string]string{
					"KMS_REGION":     "us-east-1",
					"KMS_ACCOUNT_ID": "123456789012",
				},
				Healthcheck: &composeHealthcheck{
					Test:     []string{"CMD-SHELL", "wget -qO- http://localhost:8080/ || exit 0"},
					Interval: "5s",
					Timeout:  "3s",
					Retries:  5,
				},
			},
			"aws-mocks": {
				Image: awsMocks,
				Ports: []string{"4000:4000", "1338:1338"},
				Environment: map[string]string{
					"UPSTREAM_KMS_URL":      "http://local-kms:8080",
					"KMS_PROXY_LISTEN_ADDR": ":4000",
					"IMDS_LISTEN_ADDR":      ":1338",
				},
				DependsOn: map[string]struct {
					Condition string `yaml:"condition"`
				}{
					"local-kms": {Condition: "service_healthy"},
				},
				Healthcheck: &composeHealthcheck{
					Test:     []string{"CMD-SHELL", "wget -qO- http://localhost:4000/health && wget -qO- http://localhost:1338/health"},
					Interval: "5s",
					Timeout:  "3s",
					Retries:  5,
				},
			},
			"localstack": {
				Image: "localstack/localstack:4.14",
				Ports: []string{"4566:4566"},
				Environment: map[string]string{
					"SERVICES": "ssm,sts,s3,cloudformation,iam,logs",
					"LOCALSTACK_ACKNOWLEDGE_ACCOUNT_REQUIREMENT": "1",
				},
				Healthcheck: &composeHealthcheck{
					Test:     []string{"CMD-SHELL", "curl -sf http://localhost:4566/_localstack/health || exit 1"},
					Interval: "5s",
					Timeout:  "3s",
					Retries:  20,
				},
			},
			"test-runner": {
				Image:       testRunner,
				Privileged:  true,
				NetworkMode: "host",
				Volumes: []string{
					"../../.enclave/artifacts:/data:ro",
				},
				// network_mode=host means compose-internal DNS (aws-mocks,
				// localstack, local-kms) won't resolve. Reach the helpers
				// via 127.0.0.1:<published-port> instead.
				Environment: map[string]string{
					"ENCLAVE_APP_NAME":      cfg.Name,
					"ENCLAVE_DEPLOYMENT":    cfg.Deployment,
					"AWS_ENDPOINT_URL_KMS":  "http://127.0.0.1:4000",
					"AWS_ENDPOINT_URL_SSM":  "http://127.0.0.1:4566",
					"AWS_ENDPOINT_URL_STS":  "http://127.0.0.1:4566",
					"AWS_ENDPOINT_URL_S3":   "http://127.0.0.1:4566",
					"AWS_ENDPOINT_URL_LOGS": "http://127.0.0.1:4566",
					"AWS_ACCESS_KEY_ID":     "test",
					"AWS_SECRET_ACCESS_KEY": "test",
					"AWS_REGION":            "us-east-1",
					"IMDS_PROXY_TARGET":     "127.0.0.1:1338",
				},
				DependsOn: healthy,
			},
		},
	}
}
