package cli

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
)

// tofuVars represents the variables passed to OpenTofu via terraform.tfvars.json.
type tofuVars struct {
	Region            string         `json:"region"`
	Account           string         `json:"account"`
	Deployment        string         `json:"deployment"`
	AppName           string         `json:"app_name"`
	InstanceType      string         `json:"instance_type"`
	Local             bool           `json:"local"`
	Secrets           []SecretConfig `json:"secrets"`
	MigrationCooldown string         `json:"migration_cooldown"`
	ExpectedPCR0      string         `json:"expected_pcr0,omitempty"`

	// GitHub Release coordinates for build artifacts (EIF, supervisor).
	GithubOwner string `json:"github_owner"`
	GithubRepo  string `json:"github_repo"`
	ReleaseTag  string `json:"release_tag"`
	GithubToken string `json:"github_token,omitempty"`

	// Local artifact overrides (skip GitHub download when set).
	EIFPath              string `json:"eif_path,omitempty"`
	SupervisorBinaryPath string `json:"supervisor_binary_path,omitempty"`

	// TLS settings for the enclave's public HTTPS listener, applied at
	// deploy time (tofu stores them in SSM; the runtime reads them at boot).
	TLS tofuTLSVars `json:"tls"`
}

// tofuTLSVars mirrors enclave.yaml's tls: block for the OpenTofu module.
type tofuTLSVars struct {
	FQDN     string `json:"fqdn"`
	Provider string `json:"provider"`
	Email    string `json:"email"`
}

// tofuDir returns the absolute path to the tofu/ directory at the repo root.
func tofuDir(root string) string {
	return filepath.Join(root, "tofu")
}

// writeTofuVars writes the terraform.tfvars.json file from the config.
//
// When remote is true, EIFPath and SupervisorBinaryPath are left empty so
// the tofu module's null_resource.download_artifacts pulls image.eif and
// supervisor from the GitHub Release at apply time
// (see cli/tofu_files.go: locals.use_local). The github_owner/github_repo/
// release_tag fields supply the URL coordinates.
func writeTofuVars(cfg *Config, root string, remote bool) error {
	absRoot, err := filepath.Abs(root)
	if err != nil {
		return fmt.Errorf("resolve repo root: %w", err)
	}

	vars := tofuVars{
		Region:            cfg.Region,
		Account:           cfg.Account,
		Deployment:        cfg.Prefix,
		AppName:           cfg.Name,
		InstanceType:      cfg.InstanceType,
		Local:             os.Getenv("LOCAL_DEPLOYMENT") == "true",
		Secrets:           cfg.Secrets,
		MigrationCooldown: cfg.MigrationCooldown,
		ExpectedPCR0:      readPCR0FromArtifacts(absRoot),

		GithubOwner: cfg.App.NixOwner,
		GithubRepo:  cfg.App.NixRepo,
		ReleaseTag:  cfg.App.ReleaseTag,

		TLS: tofuTLSVars{
			FQDN:     cfg.TLS.FQDN,
			Provider: cfg.TLS.Provider,
			Email:    cfg.TLS.Email,
		},
	}

	if !remote {
		// Local mode: point tofu at the artifacts produced by `enclave build`.
		vars.EIFPath = filepath.Join(absRoot, ".enclave", "artifacts", "image.eif")
		vars.SupervisorBinaryPath = filepath.Join(absRoot, ".enclave", "artifacts", "supervisor")
	}

	data, err := json.MarshalIndent(vars, "", "  ")
	if err != nil {
		return fmt.Errorf("marshal tfvars: %w", err)
	}

	tfvarsPath := filepath.Join(tofuDir(root), "terraform.tfvars.json")
	if err := os.WriteFile(tfvarsPath, data, 0644); err != nil {
		return fmt.Errorf("write tfvars: %w", err)
	}

	// Generate backend config with actual values so tofu init needs no flags.
	if !vars.Local && vars.Account != "" {
		bucket := fmt.Sprintf("%s-%s-tfstate-%s-%s", vars.Deployment, vars.AppName, vars.Account, vars.Region)
		table := fmt.Sprintf("%s-%s-tfstate-lock", vars.Deployment, vars.AppName)
		backendCfg := fmt.Sprintf(`# Auto-generated by enclave build — do not edit.
terraform {
  backend "s3" {
    bucket         = %q
    key            = "terraform.tfstate"
    region         = %q
    dynamodb_table = %q
  }
}
`, bucket, vars.Region, table)
		backendPath := filepath.Join(tofuDir(root), "backend.tf")
		if err := os.WriteFile(backendPath, []byte(backendCfg), 0644); err != nil {
			return fmt.Errorf("write backend.tf: %w", err)
		}
	}

	return nil
}

// TofuOutputs represents the parsed output from tofu output -json.
// Keys are output names, values are the output values as strings.
type TofuOutputs map[string]string

// tofuOutputJSON is the raw JSON structure from tofu output -json.
type tofuOutputJSON map[string]struct {
	Value interface{} `json:"value"`
	Type  interface{} `json:"type"`
}

// loadTofuOutputs runs tofu output -json and parses the result.
// It also caches the result to tofu/tofu-outputs.json for offline reads.
func loadTofuOutputs(root string) (TofuOutputs, error) {
	dir := tofuDir(root)

	cmd := exec.Command("tofu", "-chdir="+dir, "output", "-json")
	cmd.Stderr = os.Stderr
	data, err := cmd.Output()
	if err != nil {
		// Fall back to cached outputs.
		return loadCachedTofuOutputs(root)
	}

	var raw tofuOutputJSON
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parse tofu output: %w", err)
	}

	outputs := make(TofuOutputs)
	for k, v := range raw {
		outputs[k] = fmt.Sprintf("%v", v.Value)
	}

	// Cache for offline reads.
	cacheData, _ := json.MarshalIndent(outputs, "", "  ")
	cachePath := filepath.Join(tofuDir(root), "tofu-outputs.json")
	_ = os.WriteFile(cachePath, cacheData, 0644)

	return outputs, nil
}

// loadCachedTofuOutputs reads the cached tofu-outputs.json file.
func loadCachedTofuOutputs(root string) (TofuOutputs, error) {
	data, err := os.ReadFile(filepath.Join(tofuDir(root), "tofu-outputs.json"))
	if err != nil {
		return nil, fmt.Errorf("cannot read tofu outputs: %w (run 'tofu apply' first)", err)
	}
	var outputs TofuOutputs
	if err := json.Unmarshal(data, &outputs); err != nil {
		return nil, fmt.Errorf("invalid tofu-outputs.json: %w", err)
	}
	return outputs, nil
}

// getOutput reads a value from OpenTofu outputs.
func (o TofuOutputs) getOutput(key string) string {
	return o[key]
}

// readPCR0FromArtifacts reads PCR0 from .enclave/artifacts/pcr.json if it exists.
// Returns empty string if the file is missing (e.g. before first build).
func readPCR0FromArtifacts(root string) string {
	data, err := os.ReadFile(filepath.Join(root, ".enclave", "artifacts", "pcr.json"))
	if err != nil {
		return ""
	}
	var pcrs struct {
		PCR0 string `json:"PCR0"`
	}
	if json.Unmarshal(data, &pcrs) != nil {
		return ""
	}
	return pcrs.PCR0
}
