name: Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Unit tests (cli)
        run: go test -v -race -count=1 ./cli/...

      - name: Unit tests (runtime)
        run: cd runtime && go test -v -race -count=1 ./...

      - name: Unit tests (supervisor)
        run: go test -v -race -count=1 ./supervisor/...

      - name: Unit tests (client)
        run: cd client && go test -v -race -count=1 ./...
